image: python

stages:
  - generate
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "234123-tests-generator"

generate_tests:
  stage: generate
  script:
    - cd hw1/generators
    - python3 ${command}.py
  parallel:
    matrix:
      - command: [ "verify", "compress", "hash", "format" ]
  artifacts:
    untracked: true

publish_results:
  stage: publish
  dependencies:
    - generate_tests
  script:
    - git config user.email $RUNNER_EMAIL
    - git config user.name "ci-bot"
    - git remote add gitlab_origin https://$RUNNER_USERNAME:$ACCESS_TOKEN@gitlab.com/jamalabo1/technion-utils.git
    - BRANCH_ID="tests-$(cat /proc/sys/kernel/random/uuid)"
    - git checkout $BRANCH_ID
    - git add .
    - git commit -m "push back from pipeline"
    - git checkout $BRANCH_ID
    - git push --force gitlab_origin $BRANCH_ID -o ci.skip